const carData=[
    {
        id:0,
        name:"",
        price:"",
        location:"",
        description:"",
        owner_name:"shruti",
        owner_phone:2268832432,
        owner_email:"shrutiitaliya31@gmail.com"
    },
    {
        id:1,
        name:"",
        price:"",
        location:"",
        description:"",
        owner_name:"shruti",
        owner_phone:2268832432,
        owner_email:"shrutiitaliya31@gmail.com"
    },
    {
        id:2,
        name:"",
        price:"",
        location:"",
        description:"",
        owner_name:"shruti",
        owner_phone:2268832432,
        owner_email:"shrutiitaliya31@gmail.com"
    }
]